server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LLDBMS
    username: postgres
    password: Sinha@12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: BOOK-MY-SHOW
